# Generated by Django 4.1.1 on 2024-08-20 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='disabled', max_length=255)),
                ('token', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('consumer_process_pid', models.IntegerField()),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('port_number', models.IntegerField(unique=True)),
                ('inference_client_name', models.CharField(max_length=255, unique=True)),
                ('deploy_status', models.CharField(default='Deploying', max_length=255)),
                ('f_application_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract_metadata.application')),
            ],
            options={
                'db_table': 'position',
            },
        ),
    ]
