# Generated by Django 4.1.1 on 2024-08-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_metadata', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='uid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='consumer_process_pid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
