# Generated by Django 4.1.1 on 2024-08-21 04:08

from django.db import migrations, models
import main.apps.abstract_metadata.models.position


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_metadata', '0003_remove_topic_id_alter_application_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='port_number',
            field=models.IntegerField(default=main.apps.abstract_metadata.models.position.create_port_number, unique=True),
        ),
    ]
