# Generated by Django 4.1.1 on 2024-08-27 03:21

from django.db import migrations, models
import main.apps.abstract_metadata.models.application


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_metadata', '0004_alter_position_port_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='token',
            field=models.CharField(blank=True, default=main.apps.abstract_metadata.models.application.create_token, max_length=36),
        ),
    ]
