# Generated by Django 4.1.1 on 2024-08-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abstract_metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=255)),
                ('version', models.FloatField()),
                ('performance', models.FloatField()),
                ('access_token', models.CharField(max_length=255)),
                ('source', models.UUIDField(blank=True)),
                ('inference_environment_uid', models.UUIDField()),
                ('inference_template_uid', models.UUIDField()),
                ('f_application_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstract_metadata.application')),
            ],
            options={
                'db_table': 'model',
            },
        ),
    ]
