# Generated by Django 4.1.1 on 2024-08-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='model',
            name='source',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='uid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
