# Generated by Django 4.1.1 on 2024-08-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_metadata', '0002_alter_model_created_time_alter_model_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='file_extension',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
