# Generated by Django 4.1.1 on 2024-09-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_metadata', '0003_model_file_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='inference_environment_uid',
        ),
    ]
